### ISSUE TITLE
Facebook ignore my og tags.

### ISSUE THREAD

**Issue by Ethaan** [manuel-schoebel/ms-seo#75]
Hi Manuel.

Im having some troubles to make facebook recognize my og tags.

![screen shot 2015-10-25 at 1 17 20 pm](https://cloud.githubusercontent.com/assets/8289486/10717059/d0a23a3a-7b1a-11e5-84b5-d9dba58ab0db.png)

if you see the image the og is there.

but on facebooks it looks like this.

![screen shot 2015-10-25 at 1 18 36 pm](https://cloud.githubusercontent.com/assets/8289486/10717062/ef831a28-7b1a-11e5-9eda-b43d180196e6.png)

is there something im missing?

This is how my SEO config looks.

``` javascript
SEO.set({
            title: dataToSeo.slug,
            rel_author: ownerUrlSocialAuthor,
            meta: {
              'description': dataToSeo.proposition
            }
            og: {
              'title': dataToSeo.slug,
              'description': dataToSeo.preposition,
              'image': url + query.url()
            },
            twitter: {
              'title': dataToSeo.slug,
              'description': dataToSeo.preposition,
              'image': url + query.url(),

            }
          });
```

**NOTE** Already try also with `?_escaped_fragment_=` and it looks ok

Thanks!

**Comment by maksimkurb** [comment]
May be it can be done in `fastrender` way? We should wait for data and SEO to fetch/compute and only then return html page with meta tags already included

**Comment by rafadorado** [comment]
:+1:  Same problem here.

**Comment by kevohagan** [comment]
@rafadorado  this could be maybe a good alternative , i've been using it and its pretty smooth sailing : https://github.com/kadirahq/meteor-dochead

**Comment by Ethaan** [comment]
Using this package with [Prerender](https://atmospherejs.com/dfischer) works great

**Comment by rafadorado** [comment]
Thanks!  I'll check your ideas,  i just want time to migrate everything Flow Router!!

Anyway, I fixed it by waiting the subscription ready in the action of the route. this way Iron Router render the page when the model is loaded. 

`
  action: function(){
    var subOffer = OfferSubs.subscribe('OfferFromSlug',offerSlug);
		if(subOffer.ready()){
`
